sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-001
env:
  global:
    -
      # LTD_AWS_ID
      secure: VI5okFDv9Sm30FSJFRENdvvZxnGgb5Au2vXJRoggnqoPjMQEfg6mtURZjZOb/RuaxNk5+NmebZdoNVftGPJ4BEgqiV+CflSFNZnp6SrseDxVH+6V80eXd7zHrpsfCmMIBWGH8b0pmGxOS9eB9/ekUFWPDgNiRM0pQDrU/VadnYj61RA8WXrS/glQdTzYGP3QvrwPePFRvyT/XXvn08ugAjyYTo38ZJ6WoGiKxBk5dUqRdvbQ0ce6meznhtw9p6KZ/ZLXzPpTcjenSr19sUz1LxJf24NZjqPkVtgzR0jRIHK3NgxB3cmPU6bHbHAyKDPXte2VWhCpv556Mz6KiWgaFtgQr/hS2qvncCSx8FoQv+t+stDNws17XVWagK5e+PEgh++PMe4twdp9sGsbLyKa6PLorZbyq+tAmqYW0ASo4sM0TqjyDwPhgqF10meo8UpSyCxOlQorzWl9xA+oyPFSDiF4+fkOAi6mUZn2x27dKkBEfjgLkIOcMqewC/oFIpjD+TZdvxbCH4tyBu7e6ozIHTuGGKyLW4zmiBiR8RytqKm80GaTYlOwfRKN0Hfw5/d6XRLDh7aIm1a4wNa+O8sTutMmmFLH9ee8++SBfeXXOkVXSi/4OdJuy+xZzsrCLBcNKHTAr/O5bl5o13V+Y1bcgUUVH/7C4QpdxKn6nwhVl+4=
    -
      # LTD_AWS_SECRET
      secure: jWua2xgCM5G5lsRgMS94MdPGez5HbEcS6xelDm8SXrOZqeLC+gTMXMvbrkMxjVSW+GcOTr23h80ZBm0yOFd7E6dXvmKGrySA71XRtWHdTvI2R5D4StZfSCQHva2F4kC4C7JC9urtW/BL24h311gQd5w5qAKE4rzKUw7qCdyr2avJfG3z6zWiPR5WEZgbw82a9ZfTLbuOy60pJvBh9PIlKptCa07B+cQNgX1DsLuGW5In/zlsP2rrh6H5BfDQHN057e6aZYe7zdjQPvWxO3fPhT5f5Y14uwlO5MpKdZj3l5Ej6PQcI9bOWjr0H5YGbWYWvVepTZm+mWvYU2mMxfKDjykvMUbYoz+DIeX7kJUiTZ409CTsX7wQp3ccScWYbmnukcXmpIjAPpY/gTKfLi9WrUSdIUtYps2DztXEY+YbsDfsNAAAMAwrTpkrGmcOmtEipFQd8gxKitEWms43QNbzyPM8ubx7OmNR+UUqo2SNOTahU+8PO3wl6RWZiJfajBBUHti7B5kGEshGPAgN0/ZnIIIGb71NySdDA/Wv/kavio1oUyPrJjvwKBU4Zo6UD39rSkuEgbTVaGOGMbduN1zqH1YbKZhqlIySUCq7m/1cvOALBuDezjnigeAJx6kMk8E4CWVvjyCoExP2f1Jv+H3pIdAdPEQWV+ruE/xIqKL8c5A=
    -
      # LTD_USERNAME
      secure: roCMSrPUcYW3Puyi7cgKOZMIUWQd9R7BeRfSV3FT2ikrClcQ/O7amfpefMDWnxeWbxEblUvNw0xQmqkBL+k8co5WFlUcz7FGtkG0h4WkMei0pd1AD8qVCjDPWVQ1j1yHBivQIfwAijk2KoElZQWO/oLh2c3SDTnuBHWqWEfzmwT052w1fi3scl06Asj6YTk1hS50dXTj45CMM+1xCX8ei6qY9vW002yEW6p4+5J2WssiKqyeU1ZQa2PpWMUDiy35vWQ0jxsdIn8Ok0h1CU8EdSYSDpgcaL5VIJvIF2s2cATZaYdNG35hvARj8MAgVI0vTF4Qm/5bB/j3fUdDDWE7+FDZhrJXVz32euqiAgRb0rqNEpLNMRS+eQbcj4fgog5WROgW7bDsj+TRWfDTss7b6JHad4JEy784EL3cPHOIn8Co45tdwv5fJlkRA/X+qPlTY+AD3lT2KCYEHIDiEda6WTMObCSoFK+DQ0l3E+6P9eNzSZP0RXsc07ubhUfVF9kPu/uPuJxfpvdbBj80nfaL+79PkZMEtCY7d4iA1CUd4/jUnWFaQUgF47cCM3Z6b2dyrgJJHHPvltBCi73G+E2fWFwp8NJRUNE2kPYm2VgVwcxBiE2om6c5TZ0qTPVqtAb5PmMxeJk5zZkM+GLzDVgRy+JJCsnrdnUFG36x28v6734=
    -
      # LTD_PASSWORD
      secure: Nkem8P6NJ2rQ0M6F1rU828olf4v/3GTivM/ohSMWHK7GuAVEhYF25BZijiglCIWJbkESLXoRla1tMzb3izl9rYyqfzoHY9UiRBC4AiimUdRhCtf8rnX/k9BMU8rSroB0S0XTJc7GaL0kE1EJ+g6vLEhUv5oQ7fcy0pY896hTLqBzXamvqJ71JAA7tiUWlUHVabvc4Py0P6Y+k9QryW6kDZoNwN1jKiAzoHIZuhcQlMUG+zfsE04u2XaXfy1cUxv4u1dlk4dOjCyTzc+LD9b9rvh9ai9kRNRgqrRX0490N4jwBMTNmi3pwulion4N2YFIdTt3a1/g+81lFAni/t8cP1o17iAp5LRiVl1WDBmPx3ipzifhT29K1BYBxwplo7jWEwXQ8noPELSPgs7x9SVUSWiNH33wCiyPa4Xp0fzATXgFayQoPL0vsb2pSvHiKm8hbhhtM0LYE9/gQh+nhmPuOOmBTSPN4XXycOSvK4NE389pryoqn5nR8dP7QR7chlCcZ6RShobK9iVu/rf4T1es5Qzhbkute0dHaBNNP7YVyjUOBVkDJCm+7fVGAdbrd+TbDgTwzYyBx+7B7t6TxQsAYRDZPAyhxeTYlKSjM3l1Idj+3ziJ0crqviG9LiCSu00NKXWeJe9Ri+lwh8ed8n4GTcJG7NgGV3JMTZu6xfqzENY=
